language: python
python:
  - 2.7
  - 3.6
sudo: false

env:
    - TEST_DIR="tests"

# Setup anaconda
before_install:
  - pip install --upgrade pip;
  - pip install -r requirements.txt

install:
  # - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib ipywidgets
  - export PATH=$PWD/simpeg:$PATH

# Run test
script:
  - travis_wait 20 nosetests $TEST_DIR -v -s

notifications:
  slack: ubcgif:1Z2lR3XYRSM3GHflG71ZHEN6
