name: geosci-labs

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - ipywidgets>=0.6.0
  - requests
  - mkl
  - discretize
  - SimPEG<0.14
  - pymatsolver
  - pip
  - pip:
    - deepdish
    - empymod
    - geosci-labs
