name: geosci-labs

channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - numpy
  - scipy
  - matplotlib
  - Pillow
  - jupyter
  - ipywidgets>=0.6.0
  - requests
  - SimPEG>=0.14.2
  - empymod>=2.0.0
  - cvxopt
  - pytest
  - pip
  - pip:
    - deepdish
    - geoscilabs>=0.2.0
    - testipynb
