name: gpgLabs-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pip:
    - git+https://github.com/simpeg/geoana@magnetic_pole
    - git+https://github.com/geoscixyz/gpgLabs@magnetic_applet
